runtime: python27
api_version: 1
threadsafe: true

manual_scaling:
  instances: 1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- Makefile
- README\.md
- requirements\.txt
- dev_appserver\.py
- env/
- lib/

handlers:
- url: /_ah/.*
  script: main.app
- url: /cron
  script: main.app
- url: /.well-known/acme-challenge/.*
  script: main.app

libraries:
- name: pycrypto
  version: latest
