runtime: python27
api_version: 1
threadsafe: true

env_variables:
  # needs to match handlers url below
  LE_PATH: /08dd45ed-bbf1-43f5-add7-11a4765c44a9

  DISCOVERY: https://acme-staging-v02.api.letsencrypt.org/directory
  #DISCOVERY: https://acme-v02.api.letsencrypt.org/directory

  DOMAIN: l.kx.coremem.com

handlers:
- url: /08dd45ed-bbf1-43f5-add7-11a4765c44a9
  script: main.app

libraries:
- name: pycrypto
  version: latest
