service: gaele

runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DISCOVERY: https://acme-staging-v02.api.letsencrypt.org/directory
  #DISCOVERY: https://acme-v02.api.letsencrypt.org/directory

  DOMAIN: l.kx.coremem.com

handlers:
- url: /.*
  script: main.app

libraries:
- name: pycrypto
  version: latest
